import { AppDataSource } from '../src/config/data-source';
import { SalesReturn } from '../src/entities/SalesReturn';
import { TallySync } from '../src/entities/TallySync';

async function debugGeneration() {
  await AppDataSource.initialize();
  const returnNumber = 'SRET2627000049';
  
  const srRepo = AppDataSource.getRepository(SalesReturn);
  const syncRepo = AppDataSource.getRepository(TallySync);
  
  const sr = await srRepo.findOne({ where: { return_number: returnNumber } });
  if (!sr) {
    console.log('Return not found');
    process.exit(0);
  }
  
  console.log('Checking existing syncs for type sales_return...');
  const existing = await syncRepo.findOne({ 
    where: { 
      invoice_number: returnNumber,
      record_type: 'sales_return'
    } 
  });
  
  console.log('Existing Sync Record:', existing ? 'FOUND' : 'NOT FOUND');
  
  if (!existing) {
    console.log('This record SHOULD be generated by generateSalesReturnSyncRecords');
  }
  
  process.exit(0);
}

debugGeneration().catch(console.error);
